version: '3.1'

services: 
    web:
        build: .
        ports:
            - "8000:8000"
            - "587:587"
        environment:
            - OUTLOOK_USER=${OUTLOOK_USER}
            - OUTLLOK_PASSWORD=${OUTLOOK_PASSWORD}
        volumes:
            - .:/app